"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "tr" | "en" | "ru" | "de"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Update translations with more SEO-focused content and keywords
const translations = {
  tr: {
    "site.title": "Efe GSM Alanya",
    "site.subtitle": "Profesyonel GSM Hizmetleri",
    "nav.home": "Ana Sayfa",
    "nav.services": "Hizmetler",
    "nav.about": "Hakkımızda",
    "nav.contact": "İletişim",
    "header.currency": "Döviz",
    "header.exchange.rates": "Döviz Kurları",
    "hero.title": "30 Dakikada Telefon Tamiri",
    "hero.subtitle": "Alanya'nın En Hızlı GSM Servisi",
    "hero.description":
      "iPhone, Samsung, Huawei, Xiaomi ve tüm marka telefonlar için profesyonel tamir hizmeti. Ekran değişimi, batarya tamiri, su hasarı onarımı. Garantili ve uygun fiyatlı çözümler.",
    "services.repair": "Telefon Tamiri",
    "services.sim": "Sim Kart Satışı",
    "services.accessories": "Telefon Aksesuarları",
    "contact.whatsapp": "WhatsApp Destek",
    "contact.telegram": "Telegram Destek",
    "blog.title": "Teknoloji Haberleri ve İpuçları",
    "blog.back": "Geri Dön",
    "blog.readmore": "Devamını Oku",
    "footer.rights": "Tüm Hakları Saklıdır",
    "services.repair.desc": "Ekran kırığı, batarya sorunu, su hasarı, şarj problemi ve daha fazlası",
    "services.sim.desc": "Turkcell, Vodafone, Türk Telekom ön ödemeli hatlar",
    "services.accessories.desc": "Powerbank, telefon kılıfı, kulaklık, şarj cihazı ve daha fazlası",
    "about.title": "Hakkımızda",
    "about.description":
      "Efe GSM olarak Alanya'da 2019'dan beri kaliteli GSM hizmeti veriyoruz. Tüm marka telefonlar için hızlı tamir, garantili işçilik ve uygun fiyatlarla hizmetinizdeyiz.",
    "contact.title": "İletişim",
    "contact.address": "Adres",
    "contact.phone": "Telefon",
    "contact.email": "E-posta",
    "seo.keywords": "telefon tamiri, ekran değişimi, batarya tamiri, gsm servisi, alanya telefon tamir",
    
    // Homepage specific
    "features.30min": "30 Dakika Garanti",
    "features.30min.desc": "Ekran değişimi ve çoğu tamir işlemi 30 dakikada tamamlanır",
    "features.6month": "6 Ay Garanti",
    "features.6month.desc": "Tüm tamir işlemlerimizde 6 aya kadar garanti veriyoruz",
    "features.original": "Orijinal Parça",
    "features.original.desc": "Sadece orijinal ve kaliteli yedek parçalar kullanıyoruz",
    "features.experience": "5 Yıl Tecrübe",
    "features.experience.desc": "Alanya'da 5 yıldır güvenilir GSM hizmeti veriyoruz",
    "services.duration.30min": "30 dk",
    "services.duration.5min": "5 dk",
    "services.duration.instant": "Anında",
    "services.keywords.repair": "iPhone tamir, Samsung tamir, ekran değişimi, batarya tamiri",
    "services.keywords.sim": "Turkcell, Vodafone, Türk Telekom, ön ödemeli hat",
    "services.keywords.accessories": "powerbank, telefon kılıfı, kulaklık, şarj cihazı",
    "phonemodels.title": "Desteklediğimiz Telefon Modelleri",
    "phonemodels.subtitle": "Tüm marka ve modeller için profesyonel tamir hizmeti",
    "services.title": "Hizmetlerimiz",
    "services.subtitle": "Alanya'da en kapsamlı GSM hizmetleri",
    "services.viewall": "Tüm Hizmetleri Gör",
    "seo.repair.title": "Alanya'da Telefon Tamiri",
    "seo.repair.content1": "Efe GSM Alanya olarak, şehrimizde en hızlı ve güvenilir telefon tamiri hizmeti sunuyoruz. iPhone tamiri, Samsung tamiri, Huawei tamiri ve diğer tüm marka telefonlar için profesyonel çözümler sağlıyoruz.",
    "seo.repair.content2": "Ekran değişimi, batarya tamiri, su hasarı onarımı gibi tüm tamir işlemlerinde orijinal parça kullanımı ve uzun süreli garanti ile hizmet veriyoruz. Alanya merkez konumumuzda, hem yerli hem de yabancı müşterilerimize çok dilli destek sağlıyoruz.",
    "seo.why.title": "Neden Efe GSM?",
    "seo.why.feature1": "30 dakika garanti ile hızlı ekran değişimi",
    "seo.why.feature2": "Orijinal parça kullanımı ve kalite garantisi",
    "seo.why.feature3": "Çok dilli hizmet (Türkçe, İngilizce, Rusça, Almanca)",
    "seo.why.feature4": "Şeffaf hizmet ve dürüst yaklaşım",
    "seo.why.feature5": "6 aya kadar garanti tüm tamir işlemlerinde",
    "cta.title": "Telefonunuz Bozuldu mu?",
    "cta.subtitle": "Hemen iletişime geçin, profesyonel çözümler sunalım!",
    "cta.location": "📍 Alanya Merkez | 📞 +90 532 368 15 55 | ⏰ Pazartesi-Cumartesi 09:00-19:00",
    
    // Services page specific
    "services.page.title": "Hizmetlerimiz",
    "services.page.subtitle": "Profesyonel ve güvenilir hizmetlerimiz",
    "repair.screen": "Ekran Değişimi",
    "repair.screen.desc": "Kırık veya çatlak ekranları profesyonel şekilde değiştiriyoruz",
    "repair.battery": "Batarya Değişimi",
    "repair.battery.desc": "Orijinal bataryalarla değişim hizmeti",
    "repair.water": "Su Hasarı Tamiri",
    "repair.water.desc": "Suya düşen telefonlar için özel temizlik ve tamir",
    "duration.30min": "30 dakika",
    "duration.20min": "20 dakika",
    "duration.2to4hours": "2-4 saat",
    "warranty.6months": "6 ay garanti",
    "warranty.1year": "1 yıl garanti",
    "warranty.3months": "3 ay garanti",
    "sim.turkey": "Türkiye Hatları",
    "sim.turkey.desc": "Turkcell, Vodafone, Türk Telekom ön ödemeli hatlar",
    "sim.international": "Uluslararası Hatlar",
    "sim.international.desc": "Rusya, Almanya, İngiltere ve diğer ülkeler için",
    "features.instant": "Anında aktivasyon",
    "features.packages": "Farklı paket seçenekleri",
    "features.turkish": "Türkçe destek",
    "features.multilang": "Çok dilli destek",
    "features.roaming": "Uygun roaming",
    "features.easy": "Kolay kullanım",
    "accessories.protection": "Koruma",
    "accessories.charging": "Şarj Ürünleri",
    "accessories.audio": "Ses Ürünleri",
    "items.glass": "Temperli cam",
    "items.case": "Telefon kılıfı",
    "items.waterproof": "Su geçirmez kılıf",
    "items.powerbank": "Powerbank",
    "items.wireless": "Kablosuz şarj cihazı",
    "items.cable": "Hızlı şarj kablosu",
    "items.bluetooth": "Bluetooth kulaklık",
    "items.wired": "Kablolu kulaklık",
    "items.speaker": "Hoparlör",
    "cta.service.title": "Hizmet Almak İster misiniz?",
    "cta.service.subtitle": "Size en uygun çözümü bulmak için hemen iletişime geçin",
    "schedule": "Pazartesi - Cumartesi: 09:00 - 19:00",
    "duration": "Süre:",
    "warranty": "Garanti:",
    
    // About page specific
    "about.story.title": "Hikayemiz",
    "about.story.p1": "Efe GSM, 2019 yılında Alanya'da küçük bir dükkan olarak başladı. Kurucumuz Efe, teknoloji tutkusu ve müşteri memnuniyetini her şeyin üstünde tutan yaklaşımıyla bu yolculuğa çıktı.",
    "about.story.p2": "İlk günden itibaren '30 dakikada ekran değişimi' sloganımızla hızlı ve kaliteli hizmet verme prensibimizden ödün vermedik. Bugün binlerce mutlu müşterimizle Alanya'nın en güvenilir GSM servisi haline geldik.",
    "about.story.p3": "Sadece yerel halk değil, Alanya'yı ziyaret eden turistlere de çok dilli hizmet vererek onların tatillerinin aksamamasını sağlıyoruz.",
    "about.values.title": "Değerlerimiz",
    "about.values.subtitle": "Bizi farklı kılan değerler",
    "about.values.reliability": "Güvenilirlik",
    "about.values.reliability.desc": "Müşterilerimizin güvenini kazanmak için her zaman dürüst ve şeffaf hizmet veriyoruz.",
    "about.values.speed": "Hızlı Hizmet",
    "about.values.speed.desc": "Zamanınızın değerli olduğunu biliyoruz. Bu yüzden en hızlı şekilde hizmet vermeye odaklanıyoruz.",
    "about.values.quality": "Kalite",
    "about.values.quality.desc": "Sadece orijinal parçalar kullanıyor ve işçiliğimizin arkasında duruyoruz.",
    "about.values.customer": "Müşteri Odaklılık",
    "about.values.customer.desc": "Her müşterimizi özel hissettirmek ve ihtiyaçlarına özel çözümler sunmak önceliğimiz.",
    "about.stats.experience": "Yıl Tecrübe",
    "about.stats.customers": "Mutlu Müşteri",
    "about.stats.guarantee": "Dakika Garanti",
    "about.stats.rating": "Müşteri Puanı",
    "about.location.title": "Konumumuz",
    "about.location.address": "Alanya Merkez, Antalya",
    "about.location.desc": "Alanya'nın kalbinde, kolay ulaşılabilir konumumuzda sizleri bekliyoruz. Hem yerli hem de yabancı müşterilerimize hizmet veriyoruz.",
    "about.hours.title": "Çalışma Saatleri",
    "about.hours.weekdays": "Pazartesi - Cumartesi",
    "about.hours.time": "09:00 - 19:00",
    "about.support.title": "Dil Desteği",
    "about.why.title": "Neden Bizi Seçmelisiniz?",
    "about.why.feature1": "30 dakika garanti ile hızlı hizmet",
    "about.why.feature2": "Orijinal parça kullanımı",
    "about.why.feature3": "Çok dilli müşteri desteği",
    "about.why.feature4": "Uygun fiyat garantisi",
    "about.why.feature5": "Uzun süreli garanti",
    
    // Contact page specific
    "contact.subtitle": "Size nasıl yardımcı olabiliriz?",
    "contact.quick.title": "Hızlı İletişim",
    "contact.quick.subtitle": "Anında destek için WhatsApp veya Telegram'dan ulaşın",
    "contact.info.address.desc": "Kolay ulaşılabilir merkezi konumumuz",
    "contact.info.phone.desc": "Pazartesi - Cumartesi: 09:00 - 19:00",
    "contact.info.email.content": "info@efegsmalanya.com",
    "contact.info.email.desc": "24 saat içinde yanıt garantisi",
    "contact.info.hours.title": "Çalışma Saatleri",
    "contact.info.hours.content": "Pazartesi - Cumartesi",
    "contact.info.hours.desc": "09:00 - 19:00 (Pazar kapalı)",
    "contact.language.title": "Dil Desteği",
    "contact.language.subtitle": "Size kendi dilinizde hizmet veriyoruz",
    "contact.language.turkish": "Ana dil",
    "contact.language.english": "Akıcı",
    "contact.language.russian": "Akıcı",
    "contact.language.german": "Orta seviye",
    "contact.map.title": "Konumumuz",
    "contact.map.subtitle": "Alanya merkez konumumuzda sizleri bekliyoruz",
    "contact.details.title": "Adres Detayları",
    "contact.details.address": "Adres:",
    "contact.details.nearby": "Yakın Noktalar:",
    "contact.details.nearby.content": "Alanya Belediyesi yakını",
    "contact.details.transport": "Ulaşım:",
    "contact.details.transport.content": "Şehir merkezi, kolay ulaşım",
    "contact.details.parking": "Otopark:",
    "contact.details.parking.content": "Ücretsiz otopark imkanı",
    "contact.review": "Google'da Yorum Yap",
    "contact.hours.monday": "Pazartesi - Cuma:",
    "contact.hours.saturday": "Cumartesi:",
    "contact.hours.sunday": "Pazar:",
    "contact.hours.closed": "Kapalı",
    "contact.emergency": "Acil durumlar:",
    "contact.emergency.desc": "WhatsApp üzerinden 7/24 ulaşabilirsiniz",
  },
  en: {
    "site.title": "Efe GSM Alanya",
    "site.subtitle": "Professional GSM Services",
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.about": "About",
    "nav.contact": "Contact",
    "header.currency": "Currency",
    "header.exchange.rates": "Exchange Rates",
    "hero.title": "Phone Repair in 30 Minutes",
    "hero.subtitle": "Alanya's Fastest GSM Service",
    "hero.description":
      "Professional repair service for iPhone, Samsung, Huawei, Xiaomi and all phone brands. Screen replacement, battery repair, water damage restoration. Guaranteed and affordable solutions.",
    "services.repair": "Phone Repair",
    "services.sim": "SIM Card Sales",
    "services.accessories": "Phone Accessories",
    "contact.whatsapp": "WhatsApp Support",
    "contact.telegram": "Telegram Support",
    "blog.title": "Tech News and Tips",
    "blog.back": "Go Back",
    "blog.readmore": "Read More",
    "footer.rights": "All Rights Reserved",
    "services.repair.desc": "Screen damage, battery issues, water damage, charging problems and more",
    "services.sim.desc": "Turkcell, Vodafone, Türk Telekom prepaid lines",
    "services.accessories.desc": "Powerbank, phone cases, headphones, chargers and more",
    "about.title": "About Us",
    "about.description":
      "As Efe GSM, we have been providing quality GSM services in Alanya since 2019. Fast repair for all phone brands, guaranteed workmanship and affordable prices.",
    "contact.title": "Contact",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "seo.keywords": "phone repair, screen replacement, battery repair, gsm service, alanya phone repair",
    
    // Homepage specific
    "features.30min": "30 Minutes Guarantee",
    "features.30min.desc": "Screen replacement and most repairs completed in 30 minutes",
    "features.6month": "6 Months Warranty",
    "features.6month.desc": "We provide up to 6 months warranty on all repair services",
    "features.original": "Original Parts",
    "features.original.desc": "We only use original and quality spare parts",
    "features.experience": "5 Years Experience",
    "features.experience.desc": "Providing reliable GSM service in Alanya for 5 years",
    "services.duration.30min": "30 min",
    "services.duration.5min": "5 min",
    "services.duration.instant": "Instant",
    "services.keywords.repair": "iPhone repair, Samsung repair, screen replacement, battery repair",
    "services.keywords.sim": "Turkcell, Vodafone, Türk Telekom, prepaid line",
    "services.keywords.accessories": "powerbank, phone case, headphones, charger",
    "phonemodels.title": "Supported Phone Models",
    "phonemodels.subtitle": "Professional repair service for all brands and models",
    "services.title": "Our Services",
    "services.subtitle": "The most comprehensive GSM services in Alanya",
    "services.viewall": "View All Services",
    "seo.repair.title": "Phone Repair in Alanya",
    "seo.repair.content1": "As Efe GSM Alanya, we provide the fastest and most reliable phone repair service in our city. We provide professional solutions for iPhone repair, Samsung repair, Huawei repair and all other phone brands.",
    "seo.repair.content2": "We serve with original part usage and long-term warranty in all repair operations such as screen replacement, battery repair, water damage repair. At our central location in Alanya, we provide multilingual support to both local and foreign customers.",
    "seo.why.title": "Why Efe GSM?",
    "seo.why.feature1": "Fast screen replacement with 30 minute guarantee",
    "seo.why.feature2": "Original parts usage and quality guarantee",
    "seo.why.feature3": "Multilingual service (Turkish, English, Russian, German)",
    "seo.why.feature4": "Transparent service and honest approach",
    "seo.why.feature5": "Up to 6 months warranty on all repair services",
    "cta.title": "Is Your Phone Broken?",
    "cta.subtitle": "Contact us immediately, let us offer professional solutions!",
    "cta.location": "📍 Alanya Center | 📞 +90 532 368 15 55 | ⏰ Monday-Saturday 09:00-19:00",
    
    // Services page specific
    "services.page.title": "Our Services",
    "services.page.subtitle": "Professional and reliable services",
    "repair.screen": "Screen Replacement",
    "repair.screen.desc": "We professionally replace broken or cracked screens",
    "repair.battery": "Battery Replacement",
    "repair.battery.desc": "Battery replacement service with original batteries",
    "repair.water": "Water Damage Repair",
    "repair.water.desc": "Special cleaning and repair for phones dropped in water",
    "duration.30min": "30 minutes",
    "duration.20min": "20 minutes",
    "duration.2to4hours": "2-4 hours",
    "warranty.6months": "6 months warranty",
    "warranty.1year": "1 year warranty",
    "warranty.3months": "3 months warranty",
    "sim.turkey": "Turkey Lines",
    "sim.turkey.desc": "Turkcell, Vodafone, Türk Telekom prepaid lines",
    "sim.international": "International Lines",
    "sim.international.desc": "For Russia, Germany, England and other countries",
    "features.instant": "Instant activation",
    "features.packages": "Different package options",
    "features.turkish": "Turkish support",
    "features.multilang": "Multilingual support",
    "features.roaming": "Affordable roaming",
    "features.easy": "Easy to use",
    "accessories.protection": "Protection",
    "accessories.charging": "Charging Products",
    "accessories.audio": "Audio Products",
    "items.glass": "Tempered glass",
    "items.case": "Phone case",
    "items.waterproof": "Waterproof case",
    "items.powerbank": "Powerbank",
    "items.wireless": "Wireless charger",
    "items.cable": "Fast charging cable",
    "items.bluetooth": "Bluetooth headphones",
    "items.wired": "Wired headphones",
    "items.speaker": "Speaker",
    "cta.service.title": "Would You Like to Get Service?",
    "cta.service.subtitle": "Contact us immediately to find the most suitable solution for you",
    "schedule": "Monday - Saturday: 09:00 - 19:00",
    "duration": "Duration:",
    "warranty": "Warranty:",
    
    // About page specific
    "about.story.title": "Our Story",
    "about.story.p1": "Efe GSM was founded in 2019 as a small shop in Alanya. Our founder, Efe, started this journey with a passion for technology and a focus on customer satisfaction.",
    "about.story.p2": "From the beginning, we have not deviated from our principle of providing fast and high-quality service with our '30 minutes screen replacement' slogan. Today, we have become the most reliable GSM service in Alanya with thousands of satisfied customers.",
    "about.story.p3": "Not only local people, but we also provide multilingual service to tourists visiting Alanya.",
    "about.values.title": "Our Values",
    "about.values.subtitle": "What Differentiates Us",
    "about.values.reliability": "Reliability",
    "about.values.reliability.desc": "We always provide honest and transparent service to gain our customers' trust.",
    "about.values.speed": "Speed",
    "about.values.speed.desc": "We know the value of time. That's why we focus on providing service as quickly as possible.",
    "about.values.quality": "Quality",
    "about.values.quality.desc": "We only use original parts and ensure the quality of our workmanship.",
    "about.values.customer": "Customer Focus",
    "about.values.customer.desc": "We prioritize making each customer feel special and providing tailored solutions.",
    "about.stats.experience": "Years of Experience",
    "about.stats.customers": "Happy Customers",
    "about.stats.guarantee": "Minutes Guarantee",
    "about.stats.rating": "Customer Rating",
    "about.location.title": "Our Location",
    "about.location.address": "Alanya Center, Antalya",
    "about.location.desc": "We are waiting for you in our central location in Alanya, easily accessible to both local and foreign customers.",
    "about.hours.title": "Working Hours",
    "about.hours.weekdays": "Monday - Saturday",
    "about.hours.time": "09:00 - 19:00",
    "about.support.title": "Language Support",
    "about.why.title": "Why Choose Us?",
    "about.why.feature1": "Fast service with 30-minute guarantee",
    "about.why.feature2": "Original part usage",
    "about.why.feature3": "Multilingual customer support",
    "about.why.feature4": "Affordable price guarantee",
    "about.why.feature5": "Long-term guarantee",
    
    // Contact page specific
    "contact.subtitle": "How Can We Help You?",
    "contact.quick.title": "Quick Contact",
    "contact.quick.subtitle": "Contact us instantly via WhatsApp or Telegram",
    "contact.info.address.desc": "Our easily accessible central location",
    "contact.info.phone.desc": "Monday - Saturday: 09:00 - 19:00",
    "contact.info.email.content": "info@efegsmalanya.com",
    "contact.info.email.desc": "Guarantee of response within 24 hours",
    "contact.info.hours.title": "Working Hours",
    "contact.info.hours.content": "Monday - Saturday",
    "contact.info.hours.desc": "09:00 - 19:00 (Sunday closed)",
    "contact.language.title": "Language Support",
    "contact.language.subtitle": "We provide service in your own language",
    "contact.language.turkish": "Native language",
    "contact.language.english": "Speedy",
    "contact.language.russian": "Speedy",
    "contact.language.german": "Intermediate level",
    "contact.map.title": "Our Location",
    "contact.map.subtitle": "We are waiting for you in our central location in Alanya",
    "contact.details.title": "Address Details",
    "contact.details.address": "Address:",
    "contact.details.nearby": "Nearby Places:",
    "contact.details.nearby.content": "Near Alanya Municipality",
    "contact.details.transport": "Transportation:",
    "contact.details.transport.content": "City center, easy access",
    "contact.details.parking": "Parking:",
    "contact.details.parking.content": "Free parking opportunity",
    "contact.review": "Leave a Review on Google",
    "contact.hours.monday": "Monday - Friday:",
    "contact.hours.saturday": "Saturday:",
    "contact.hours.sunday": "Sunday:",
    "contact.hours.closed": "Closed",
    "contact.emergency": "Emergency:",
    "contact.emergency.desc": "You can reach us 24/7 via WhatsApp",
  },
  ru: {
    "site.title": "Efe GSM Алания",
    "site.subtitle": "Профессиональные GSM услуги",
    "nav.home": "Главная",
    "nav.services": "Услуги",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "header.currency": "Валюта",
    "header.exchange.rates": "Курсы валют",
    "hero.title": "Ремонт телефона за 30 минут",
    "hero.subtitle": "Самый быстрый GSM сервис в Алании",
    "hero.description":
      "Профессиональный ремонт iPhone, Samsung, Huawei, Xiaomi и всех марок телефонов. Замена экрана, ремонт батареи, восстановление после попадания воды. Гарантированные и доступные решения.",
    "services.repair": "Ремонт телефонов",
    "services.sim": "Продажа SIM-карт",
    "services.accessories": "Аксессуары для телефонов",
    "contact.whatsapp": "Поддержка WhatsApp",
    "contact.telegram": "Поддержка Telegram",
    "blog.title": "Технические новости и советы",
    "blog.back": "Назад",
    "blog.readmore": "Читать далее",
    "footer.rights": "Все права защищены",
    "services.repair.desc":
      "Повреждение экрана, проблемы с батареей, повреждение водой, проблемы с зарядкой и многое другое",
    "services.sim.desc": "Предоплаченные линии Turkcell, Vodafone, Türk Telekom",
    "services.accessories.desc": "Powerbank, чехлы для телефонов, наушники, зарядные устройства и многое другое",
    "about.title": "О нас",
    "about.description":
      "Как Efe GSM, мы предоставляем качественные GSM услуги в Алании с 2019 года. Быстрый ремонт для всех марок телефонов, гарантированная работа и доступные цены.",
    "contact.title": "Контакты",
    "contact.address": "Адрес",
    "contact.phone": "Телефон",
    "contact.email": "Электронная почта",
    "seo.keywords": "ремонт телефонов, замена экрана, ремонт батареи, gsm сервис, алания ремонт телефонов",
    
    // Homepage specific
    "features.30min": "Гарантия 30 минут",
    "features.30min.desc": "Замена экрана и большинство ремонтов выполняются за 30 минут",
    "features.6month": "Гарантия 6 месяцев",
    "features.6month.desc": "Мы предоставляем гарантию до 6 месяцев на все ремонтные услуги",
    "features.original": "Оригинальные детали",
    "features.original.desc": "Мы используем только оригинальные и качественные запчасти",
    "features.experience": "Опыт 5 лет",
    "features.experience.desc": "Предоставляем надежные GSM услуги в Алании уже 5 лет",
    "services.duration.30min": "30 мин",
    "services.duration.5min": "5 мин",
    "services.duration.instant": "Мгновенно",
    "services.keywords.repair": "ремонт iPhone, ремонт Samsung, замена экрана, ремонт батареи",
    "services.keywords.sim": "Turkcell, Vodafone, Türk Telekom, предоплаченная линия",
    "services.keywords.accessories": "powerbank, чехол для телефона, наушники, зарядное устройство",
    "phonemodels.title": "Поддерживаемые модели телефонов",
    "phonemodels.subtitle": "Профессиональные услуги ремонта для всех брендов и моделей",
    "services.title": "Наши услуги",
    "services.subtitle": "Самые комплексные GSM услуги в Алании",
    "services.viewall": "Посмотреть все услуги",
    "seo.repair.title": "Ремонт телефонов в Алании",
    "seo.repair.content1": "Как Efe GSM Алания, мы предоставляем самые быстрые и надежные услуги по ремонту телефонов в нашем городе. Мы предоставляем профессиональные решения для ремонта iPhone, Samsung, Huawei и всех других марок телефонов.",
    "seo.repair.content2": "Мы обслуживаем с использованием оригинальных деталей и долгосрочной гарантией во всех ремонтных операциях, таких как замена экрана, ремонт батареи, ремонт повреждений от воды. В нашем центральном расположении в Алании мы предоставляем многоязычную поддержку как местным, так и иностранным клиентам.",
    "seo.why.title": "Почему Efe GSM?",
    "seo.why.feature1": "Быстрая замена экрана с 30-минутной гарантией",
    "seo.why.feature2": "Использование оригинальных деталей и гарантия качества",
    "seo.why.feature3": "Многоязычный сервис (турецкий, английский, русский, немецкий)",
    "seo.why.feature4": "Прозрачный сервис и честный подход",
    "seo.why.feature5": "До 6 месяцев гарантии на все ремонтные услуги",
    "cta.title": "Ваш телефон сломан?",
    "cta.subtitle": "Свяжитесь с нами немедленно, позвольте нам предложить профессиональные решения!",
    "cta.location": "📍 Центр Алании | 📞 +90 532 368 15 55 | ⏰ Понедельник-Суббота 09:00-19:00",
    
    // Services page specific
    "services.page.title": "Наши услуги",
    "services.page.subtitle": "Профессиональные и надежные услуги",
    "repair.screen": "Замена экрана",
    "repair.screen.desc": "Мы профессионально заменяем разбитые или треснувшие экраны",
    "repair.battery": "Замена батареи",
    "repair.battery.desc": "Услуга замены батареи с оригинальными батареями",
    "repair.water": "Ремонт повреждений от воды",
    "repair.water.desc": "Специальная очистка и ремонт для телефонов, упавших в воду",
    "duration.30min": "30 минут",
    "duration.20min": "20 минут",
    "duration.2to4hours": "2-4 часа",
    "warranty.6months": "гарантия 6 месяцев",
    "warranty.1year": "гарантия 1 год",
    "warranty.3months": "гарантия 3 месяца",
    "sim.turkey": "Турецкие линии",
    "sim.turkey.desc": "Предоплаченные линии Turkcell, Vodafone, Türk Telekom",
    "sim.international": "Международные линии",
    "sim.international.desc": "Для России, Германии, Англии и других стран",
    "features.instant": "Мгновенная активация",
    "features.packages": "Различные варианты пакетов",
    "features.turkish": "Поддержка на турецком",
    "features.multilang": "Многоязычная поддержка",
    "features.roaming": "Доступный роуминг",
    "features.easy": "Простота использования",
    "accessories.protection": "Защита",
    "accessories.charging": "Зарядные продукты",
    "accessories.audio": "Аудио продукты",
    "items.glass": "Закаленное стекло",
    "items.case": "Чехол для телефона",
    "items.waterproof": "Водонепроницаемый чехол",
    "items.powerbank": "Powerbank",
    "items.wireless": "Беспроводное зарядное устройство",
    "items.cable": "Кабель быстрой зарядки",
    "items.bluetooth": "Bluetooth наушники",
    "items.wired": "Проводные наушники",
    "items.speaker": "Динамик",
    "cta.service.title": "Хотели бы получить услугу?",
    "cta.service.subtitle": "Свяжитесь с нами немедленно, чтобы найти наиболее подходящее решение для вас",
    "schedule": "Понедельник - Суббота: 09:00 - 19:00",
    "duration": "Продолжительность:",
    "warranty": "Гарантия:",
    
    // About page specific
    "about.story.title": "Наша история",
    "about.story.p1": "Efe GSM была основана в 2019 году как маленький магазин в Алании. Наш основатель, Efe, начал этот путь с патриотизмом и фокусом на удовлетворении клиентов.",
    "about.story.p2": "С самого начала мы не отклонялись от нашего принципа предоставления быстрого и высококачественного обслуживания со слоганом '30 минут замены экрана'. Сегодня мы стали самым надежным GSM сервисом в Алании с тысячами довольных клиентов.",
    "about.story.p3": "Не только местные жители, но и туристы, посещающие Аланию, получают многоязычное обслуживание, чтобы их отдых не был испорчен.",
    "about.values.title": "Наши ценности",
    "about.values.subtitle": "Что отличает нас",
    "about.values.reliability": "Надежность",
    "about.values.reliability.desc": "Мы всегда предоставляем честное и прозрачное обслуживание, чтобы завоевать доверие наших клиентов.",
    "about.values.speed": "Скорость",
    "about.values.speed.desc": "Мы знаем ценность времени. Поэтому мы сосредоточены на предоставлении обслуживания как можно быстрее.",
    "about.values.quality": "Качество",
    "about.values.quality.desc": "Мы используем только оригинальные запчасти и гарантируем качество нашей работы.",
    "about.values.customer": "Потребительское внимание",
    "about.values.customer.desc": "Мы ставим перед собой цель сделать каждого клиента особенным и предоставить индивидуальные решения.",
    "about.stats.experience": "Опыт работы",
    "about.stats.customers": "Счастливые клиенты",
    "about.stats.guarantee": "Гарантия в минутах",
    "about.stats.rating": "Рейтинг клиента",
    "about.location.title": "Наше местоположение",
    "about.location.address": "Алания, Анталия",
    "about.location.desc": "Мы ждем вас в нашем центральном месте в Алании, легко доступном как для местных, так и для иностранных клиентов.",
    "about.hours.title": "Часы работы",
    "about.hours.weekdays": "Понедельник - Суббота",
    "about.hours.time": "09:00 - 19:00",
    "about.support.title": "Поддержка языка",
    "about.why.title": "Почему Efe GSM?",
    "about.why.feature1": "Быстрая замена экрана с 30-минутной гарантией",
    "about.why.feature2": "Использование оригинальных деталей и гарантия качества",
    "about.why.feature3": "Многоязычное обслуживание клиентов",
    "about.why.feature4": "Доступная цена гарантии",
    "about.why.feature5": "Долгосрочная гарантия",
    
    // Contact page specific
    "contact.subtitle": "Как мы можем вам помочь?",
    "contact.quick.title": "Быстрый контакт",
    "contact.quick.subtitle": "Свяжитесь с нами мгновенно через WhatsApp или Telegram",
    "contact.info.address.desc": "Наше легкодоступное центральное местоположение",
    "contact.info.phone.desc": "Понедельник - Суббота: 09:00 - 19:00",
    "contact.info.email.content": "info@efegsmalanya.com",
    "contact.info.email.desc": "Гарантия ответа в течение 24 часов",
    "contact.info.hours.title": "Часы работы",
    "contact.info.hours.content": "Понедельник - Суббота",
    "contact.info.hours.desc": "09:00 - 19:00 (Воскресенье закрыто)",
    "contact.language.title": "Поддержка языка",
    "contact.language.subtitle": "Мы предоставляем обслуживание на вашем родном языке",
    "contact.language.turkish": "Родной язык",
    "contact.language.english": "Быстрый",
    "contact.language.russian": "Быстрый",
    "contact.language.german": "Средний уровень",
    "contact.map.title": "Наше местоположение",
    "contact.map.subtitle": "Мы ждем вас в нашем центральном месте в Алании",
    "contact.details.title": "Детали адреса",
    "contact.details.address": "Адрес:",
    "contact.details.nearby": "Ближайшие места:",
    "contact.details.nearby.content": "Рядом с Аланией",
    "contact.details.transport": "Транспорт:",
    "contact.details.transport.content": "Центральный город, легкодоступный",
    "contact.details.parking": "Парковка:",
    "contact.details.parking.content": "Бесплатная парковка",
    "contact.review": "Оставьте отзыв на Google",
    "contact.hours.monday": "Понедельник - Пятница:",
    "contact.hours.saturday": "Суббота:",
    "contact.hours.sunday": "Воскресенье:",
    "contact.hours.closed": "Закрыто",
    "contact.emergency": "Экстренные случаи:",
    "contact.emergency.desc": "Вы можете нам позвонить 24/7 через WhatsApp",
  },
  de: {
    "site.title": "Efe GSM Alanya",
    "site.subtitle": "Professionelle GSM-Dienstleistungen",
    "nav.home": "Startseite",
    "nav.services": "Dienstleistungen",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "header.currency": "Währung",
    "header.exchange.rates": "Wechselkurse",
    "hero.title": "Handy-Reparatur in 30 Minuten",
    "hero.subtitle": "Alanyas schnellster GSM-Service",
    "hero.description":
      "Professioneller Reparaturservice für iPhone, Samsung, Huawei, Xiaomi und alle Handy-Marken. Bildschirmaustausch, Batteriereparatur, Wasserschadenreparatur. Garantierte und erschwingliche Lösungen.",
    "services.repair": "Handy-Reparatur",
    "services.sim": "SIM-Karten-Verkauf",
    "services.accessories": "Handy-Zubehör",
    "contact.whatsapp": "WhatsApp Support",
    "contact.telegram": "Telegram Support",
    "blog.title": "Tech-News und Tipps",
    "blog.back": "Zurück",
    "blog.readmore": "Weiterlesen",
    "footer.rights": "Alle Rechte vorbehalten",
    "services.repair.desc": "Bildschirmschäden, Batterieprobleme, Wasserschäden, Ladeprobleme und mehr",
    "services.sim.desc": "Prepaid-Leitungen von Turkcell, Vodafone, Türk Telekom",
    "services.accessories.desc": "Powerbank, Handyhüllen, Kopfhörer, Ladegeräte und mehr",
    "about.title": "Über uns",
    "about.description":
      "Als Efe GSM bieten wir seit 2019 qualitativ hochwertige GSM-Dienstleistungen in Alanya an. Schnelle Reparatur für alle Handy-Marken, garantierte Arbeit und erschwingliche Preise.",
    "contact.title": "Kontakt",
    "contact.address": "Adresse",
    "contact.phone": "Telefon",
    "contact.email": "E-Mail",
    "seo.keywords": "handy reparatur, bildschirm austausch, batterie reparatur, gsm service, alanya handy reparatur",
    
    // Homepage specific
    "features.30min": "30 Minuten Garantie",
    "features.30min.desc": "Bildschirmaustausch und die meisten Reparaturen in 30 Minuten abgeschlossen",
    "features.6month": "6 Monate Garantie",
    "features.6month.desc": "Wir gewähren bis zu 6 Monate Garantie auf alle Reparaturdienstleistungen",
    "features.original": "Originalteile",
    "features.original.desc": "Wir verwenden nur originale und qualitativ hochwertige Ersatzteile",
    "features.experience": "5 Jahre Erfahrung",
    "features.experience.desc": "Seit 5 Jahren zuverlässige GSM-Dienstleistungen in Alanya",
    "services.duration.30min": "30 Min",
    "services.duration.5min": "5 Min",
    "services.duration.instant": "Sofort",
    "services.keywords.repair": "iPhone Reparatur, Samsung Reparatur, Bildschirmaustausch, Batteriereparatur",
    "services.keywords.sim": "Turkcell, Vodafone, Türk Telekom, Prepaid-Leitung",
    "services.keywords.accessories": "Powerbank, Handyhülle, Kopfhörer, Ladegerät",
    "phonemodels.title": "Unterstützte Handy-Modelle",
    "phonemodels.subtitle": "Professionelle Reparaturdienstleistungen für alle Marken und Modelle",
    "services.title": "Unsere Dienstleistungen",
    "services.subtitle": "Die umfassendsten GSM-Dienstleistungen in Alanya",
    "services.viewall": "Alle Dienstleistungen anzeigen",
    "seo.repair.title": "Handy-Reparatur in Alanya",
    "seo.repair.content1": "Als Efe GSM Alanya bieten wir den schnellsten und zuverlässigsten Handy-Reparaturservice in unserer Stadt. Wir bieten professionelle Lösungen für iPhone-Reparatur, Samsung-Reparatur, Huawei-Reparatur und alle anderen Handy-Marken.",
    "seo.repair.content2": "Wir arbeiten mit Originalteilen und langfristiger Garantie bei allen Reparaturvorgängen wie Bildschirmaustausch, Batteriereparatur, Wasserschadenreparatur. An unserem zentralen Standort in Alanya bieten wir sowohl lokalen als auch ausländischen Kunden mehrsprachige Unterstützung.",
    "seo.why.title": "Warum Efe GSM?",
    "seo.why.feature1": "Schneller Bildschirmaustausch mit 30-Minuten-Garantie",
    "seo.why.feature2": "Verwendung von Originalteilen und Qualitätsgarantie",
    "seo.why.feature3": "Mehrsprachiger Service (Türkisch, Englisch, Russisch, Deutsch)",
    "seo.why.feature4": "Transparenter Service und ehrlicher Ansatz",
    "seo.why.feature5": "Bis zu 6 Monate Garantie auf alle Reparaturdienstleistungen",
    "cta.title": "Ist Ihr Handy kaputt?",
    "cta.subtitle": "Kontaktieren Sie uns sofort, lassen Sie uns professionelle Lösungen anbieten!",
    "cta.location": "📍 Alanya Zentrum | 📞 +90 532 368 15 55 | ⏰ Montag-Samstag 09:00-19:00",
    
    // Services page specific
    "services.page.title": "Unsere Dienstleistungen",
    "services.page.subtitle": "Professionelle und zuverlässige Dienstleistungen",
    "repair.screen": "Bildschirmaustausch",
    "repair.screen.desc": "Wir tauschen kaputte oder gerissene Bildschirme professionell aus",
    "repair.battery": "Batterieaustausch",
    "repair.battery.desc": "Batterieaustauschservice mit Originalbatterien",
    "repair.water": "Wasserschadenreparatur",
    "repair.water.desc": "Spezielle Reinigung und Reparatur für ins Wasser gefallene Handys",
    "duration.30min": "30 Minuten",
    "duration.20min": "20 Minuten",
    "duration.2to4hours": "2-4 Stunden",
    "warranty.6months": "6 Monate Garantie",
    "warranty.1year": "1 Jahr Garantie",
    "warranty.3months": "3 Monate Garantie",
    "sim.turkey": "Türkei-Leitungen",
    "sim.turkey.desc": "Prepaid-Leitungen von Turkcell, Vodafone, Türk Telekom",
    "sim.international": "Internationale Leitungen",
    "sim.international.desc": "Für Russland, Deutschland, England und andere Länder",
    "features.instant": "Sofortige Aktivierung",
    "features.packages": "Verschiedene Paketoptionen",
    "features.turkish": "Türkische Unterstützung",
    "features.multilang": "Mehrsprachige Unterstützung",
    "features.roaming": "Günstiges Roaming",
    "features.easy": "Einfach zu verwenden",
    "accessories.protection": "Schutz",
    "accessories.charging": "Ladeprodukte",
    "accessories.audio": "Audioprodukte",
    "items.glass": "Gehärtetes Glas",
    "items.case": "Handyhülle",
    "items.waterproof": "Wasserdichte Hülle",
    "items.powerbank": "Powerbank",
    "items.wireless": "Kabelloses Ladegerät",
    "items.cable": "Schnellladekabel",
    "items.bluetooth": "Bluetooth-Kopfhörer",
    "items.wired": "Kabelgebundene Kopfhörer",
    "items.speaker": "Lautsprecher",
    "cta.service.title": "Möchten Sie Service erhalten?",
    "cta.service.subtitle": "Kontaktieren Sie uns sofort, um die für Sie am besten geeignete Lösung zu finden",
    "schedule": "Montag - Samstag: 09:00 - 19:00",
    "duration": "Dauer:",
    "warranty": "Garantie:",
    
    // About page specific
    "about.story.title": "Unser Geschicht",
    "about.story.p1": "Efe GSM wurde 2019 als kleiner Laden in Alanya gegründet. Unser Gründer Efe begann diesen Weg mit einer Leidenschaft für Technologie und einem Fokus auf Kundenzufriedenheit.",
    "about.story.p2": "Seit Beginn haben wir nicht von unserem Grundsatz abgewichen, schnelle und hochwertige Dienstleistungen mit unserem Slogan '30 Minuten Bildschirmaustausch' zu bieten. Heute sind wir zum zuverlässigsten GSM-Service in Alanya geworden mit Tausenden zufriedener Kunden.",
    "about.story.p3": "Nicht nur lokale Einwohner, sondern auch Touristen, die Alanya besuchen, erhalten mehrsprachige Dienstleistungen, um ihren Urlaub nicht zu ruinieren.",
    "about.values.title": "Unsere Werte",
    "about.values.subtitle": "Was uns von anderen unterscheidet",
    "about.values.reliability": "Zuverlässigkeit",
    "about.values.reliability.desc": "Wir bieten immer ehrlich und transparente Dienstleistungen, um die Vertrauen unserer Kunden zu gewinnen.",
    "about.values.speed": "Schnelligkeit",
    "about.values.speed.desc": "Wir wissen, wie wertvoll Zeit ist. Deshalb konzentrieren wir uns darauf, Dienstleistungen so schnell wie möglich zu erbringen.",
    "about.values.quality": "Qualität",
    "about.values.quality.desc": "Wir verwenden nur originale Teile und garantieren die Qualität unserer Arbeit.",
    "about.values.customer": "Kundenorientierung",
    "about.values.customer.desc": "Wir priorisieren es, jeden Kunden einzigartig zu gestalten und individuelle Lösungen zu bieten.",
    "about.stats.experience": "Erfahrung",
    "about.stats.customers": "Zufriedene Kunden",
    "about.stats.guarantee": "Garantie in Minuten",
    "about.stats.rating": "Kundenbewertung",
    "about.location.title": "Unser Standort",
    "about.location.address": "Alanya, Antalya",
    "about.location.desc": "Wir warten Sie in unserem zentralen Standort in Alanya ab, der sowohl für lokale als auch für ausländische Kunden leicht zugänglich ist.",
    "about.hours.title": "Öffnungszeiten",
    "about.hours.weekdays": "Montag - Samstag",
    "about.hours.time": "09:00 - 19:00",
    "about.support.title": "Sprachunterstützung",
    "about.why.title": "Warum Efe GSM?",
    "about.why.feature1": "Schneller Bildschirmaustausch mit 30-Minuten-Garantie",
    "about.why.feature2": "Verwendung von Originalteilen und Qualitätsgarantie",
    "about.why.feature3": "Mehrsprachiger Kundendienst",
    "about.why.feature4": "Zugängliche Preisgarantie",
    "about.why.feature5": "Langfristige Garantie",
    
    // Contact page specific
    "contact.subtitle": "Wie können wir Ihnen helfen?",
    "contact.quick.title": "Schneller Kontakt",
    "contact.quick.subtitle": "Kontaktieren Sie uns sofort über WhatsApp oder Telegram",
    "contact.info.address.desc": "Unser leicht zugängliches zentrales Standort",
    "contact.info.phone.desc": "Montag - Samstag: 09:00 - 19:00",
    "contact.info.email.content": "info@efegsmalanya.com",
    "contact.info.email.desc": "Garantie für Antwort innerhalb von 24 Stunden",
    "contact.info.hours.title": "Öffnungszeiten",
    "contact.info.hours.content": "Montag - Samstag",
    "contact.info.hours.desc": "09:00 - 19:00 (Sonntag geschlossen)",
    "contact.language.title": "Sprachunterstützung",
    "contact.language.subtitle": "Wir bieten Dienstleistungen in Ihrer eigenen Sprache",
    "contact.language.turkish": "Muttersprache",
    "contact.language.english": "Schnell",
    "contact.language.russian": "Schnell",
    "contact.language.german": "Mittelstufe",
    "contact.map.title": "Unser Standort",
    "contact.map.subtitle": "Wir warten Sie in unserem zentralen Standort in Alanya ab",
    "contact.details.title": "Adressdetails",
    "contact.details.address": "Adresse:",
    "contact.details.nearby": "Nächste Orte:",
    "contact.details.nearby.content": "In der Nähe von Alanya",
    "contact.details.transport": "Verkehr:",
    "contact.details.transport.content": "Stadtzentrum, leicht zugänglich",
    "contact.details.parking": "Parken:",
    "contact.details.parking.content": "Kostenlose Parkmöglichkeit",
    "contact.review": "Hinterlassen Sie einen Google-Bewertung",
    "contact.hours.monday": "Montag - Freitag:",
    "contact.hours.saturday": "Samstag:",
    "contact.hours.sunday": "Sonntag:",
    "contact.hours.closed": "Geschlossen",
    "contact.emergency": "Notfälle:",
    "contact.emergency.desc": "Sie können uns 24/7 über WhatsApp erreichen",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("tr")

  useEffect(() => {
    // Detect browser language
    const browserLang = navigator.language.split("-")[0] as Language
    if (["tr", "en", "ru", "de"].includes(browserLang)) {
      setLanguage(browserLang)
    }
  }, [])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
